apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
name: shortdump-analyzer-template
spec:
inputs:
parameters:
- name: "docker_image"
type: string
template:
containers:
- name: shortdump-analyzer
image: "{{ .inputs.parameters.docker_image }}"
ports:
- containerPort: 8080
resources:
limits:
cpu: "1"
memory: "1Gi"
readinessProbe:
httpGet:
path: /healthz
port: 8080
initialDelaySeconds: 5
periodSeconds: 10
